### ISSUE TITLE
What are the actual symbols pasted in to the game?

### ISSUE THREAD

**Issue by ErikHumphrey** [doubletheron/ColorfulDota#1]
I can't make my own version without this, too lazy to do some hex editor stuff

**Comment by ErikHumphrey** [comment]
nevermind i'm retarded

**Comment by 2xRon** [comment]
idk if it will copy well here but

 darkyellow   purple   green   blue   hotpink   pink   magenta   violet   lightgreen   yellow   olive   red
  white   grey   orange   limegreen

**Comment by ErikHumphrey** [comment]
yeah it doesn't copy on github but i heard it works through steam

add me up and send them, it will make my life easier

**Comment by 2xRon** [comment]
hello, it's me your redditor (2xRon)
